class Language {
  final String name;
  final String region;

  Language({required this.name, required this.region});

  @override
  String toString() => '$name ($region)';
}

final List<Language> languages = [
  Language(name: 'Afrikaans', region: 'South Africa'),
  Language(name: 'Albanian', region: 'Albania'),
  Language(name: 'Amharic', region: 'Ethiopia'),
  Language(name: 'Arabic', region: 'Middle East and North Africa'),
  Language(name: 'Armenian', region: 'Armenia'),
  Language(name: 'Awadhi', region: 'India'),
  Language(name: 'Azerbaijani', region: 'Azerbaijan'),
  Language(name: 'Bashkir', region: 'Russia'),
  Language(name: 'Basque', region: 'Spain'),
  Language(name: 'Belarusian', region: 'Belarus'),
  Language(name: 'Bengali', region: 'Bangladesh'),
  Language(name: 'Bhojpuri', region: 'India'),
  Language(name: 'Bosnian', region: 'Bosnia and Herzegovina'),
  Language(name: 'Brazilian Portuguese', region: 'Brazil'),
  Language(name: 'Bulgarian', region: 'Bulgaria'),
  Language(name: 'Burmese', region: 'Myanmar'),
  Language(name: 'Cantonese (Yue)', region: 'China'),
  Language(name: 'Catalan', region: 'Spain'),
  Language(name: 'Cebuano', region: 'Philippines'),
  Language(name: 'Chhattisgarhi', region: 'India'),
  Language(name: 'Chinese', region: 'China'),
  Language(name: 'Croatian', region: 'Croatia'),
  Language(name: 'Czech', region: 'Czech Republic'),
  Language(name: 'Danish', region: 'Denmark'),
  Language(name: 'Dogri', region: 'India'),
  Language(name: 'Dutch', region: 'Netherlands'),
  Language(name: 'English', region: 'United Kingdom'),
  Language(name: 'Esperanto', region: 'International'),
  Language(name: 'Estonian', region: 'Estonia'),
  Language(name: 'Faroese', region: 'Faroe Islands'),
  Language(name: 'Filipino', region: 'Philippines'),
  Language(name: 'Finnish', region: 'Finland'),
  Language(name: 'French', region: 'France'),
  Language(name: 'Galician', region: 'Spain'),
  Language(name: 'Georgian', region: 'Georgia'),
  Language(name: 'German', region: 'Germany'),
  Language(name: 'Greek', region: 'Greece'),
  Language(name: 'Gujarati', region: 'India'),
  Language(name: 'Hausa', region: 'Nigeria'),
  Language(name: 'Haryanvi', region: 'India'),
  Language(name: 'Hebrew', region: 'Israel'),
  Language(name: 'Hindi', region: 'India'),
  Language(name: 'Hungarian', region: 'Hungary'),
  Language(name: 'Icelandic', region: 'Iceland'),
  Language(name: 'Igbo', region: 'Nigeria'),
  Language(name: 'Indonesian', region: 'Indonesia'),
  Language(name: 'Irish', region: 'Ireland'),
  Language(name: 'Italian', region: 'Italy'),
  Language(name: 'Japanese', region: 'Japan'),
  Language(name: 'Javanese', region: 'Indonesia'),
  Language(name: 'Kannada', region: 'India'),
  Language(name: 'Kashmiri', region: 'India'),
  Language(name: 'Kazakh', region: 'Kazakhstan'),
  Language(name: 'Khmer', region: 'Cambodia'),
  Language(name: 'Kinyarwanda', region: 'Rwanda'),
  Language(name: 'Konkani', region: 'India'),
  Language(name: 'Korean', region: 'South Korea'),
  Language(name: 'Kurdish', region: 'Middle East'),
  Language(name: 'Kyrgyz', region: 'Kyrgyzstan'),
  Language(name: 'Lao', region: 'Laos'),
  Language(name: 'Latvian', region: 'Latvia'),
  Language(name: 'Lithuanian', region: 'Lithuania'),
  Language(name: 'Luxembourgish', region: 'Luxembourg'),
  Language(name: 'Macedonian', region: 'North Macedonia'),
  Language(name: 'Maithili', region: 'India'),
  Language(name: 'Malay', region: 'Malaysia'),
  Language(name: 'Malayalam', region: 'India'),
  Language(name: 'Maltese', region: 'Malta'),
  Language(name: 'Mandarin', region: 'China'),
  Language(name: 'Maori', region: 'New Zealand'),
  Language(name: 'Marathi', region: 'India'),
  Language(name: 'Marwari', region: 'India'),
  Language(name: 'Min Nan', region: 'China'),
  Language(name: 'Moldovan', region: 'Moldova'),
  Language(name: 'Mongolian', region: 'Mongolia'),
  Language(name: 'Montenegrin', region: 'Montenegro'),
  Language(name: 'Nepali', region: 'Nepal'),
  Language(name: 'Norwegian', region: 'Norway'),
  Language(name: 'Oriya', region: 'India'),
  Language(name: 'Pashto', region: 'Afghanistan'),
  Language(name: 'Persian (Farsi)', region: 'Iran'),
  Language(name: 'Polish', region: 'Poland'),
  Language(name: 'Portuguese', region: 'Portugal'),
  Language(name: 'Punjabi', region: 'India'),
  Language(name: 'Quechua', region: 'Peru'),
  Language(name: 'Rajasthani', region: 'India'),
  Language(name: 'Romanian', region: 'Romania'),
  Language(name: 'Russian', region: 'Russia'),
  Language(name: 'Sanskrit', region: 'India'),
  Language(name: 'Santali', region: 'India'),
  Language(name: 'Serbian', region: 'Serbia'),
  Language(name: 'Sindhi', region: 'Pakistan'),
  Language(name: 'Sinhala', region: 'Sri Lanka'),
  Language(name: 'Slovak', region: 'Slovakia'),
  Language(name: 'Slovene', region: 'Slovenia'),
  Language(name: 'Somali', region: 'Somalia'),
  Language(name: 'Spanish', region: 'Spain'),
  Language(name: 'Swahili', region: 'East Africa'),
  Language(name: 'Swedish', region: 'Sweden'),
  Language(name: 'Tagalog', region: 'Philippines'),
  Language(name: 'Tajik', region: 'Tajikistan'),
  Language(name: 'Tamil', region: 'India'),
  Language(name: 'Telugu', region: 'India'),
  Language(name: 'Thai', region: 'Thailand'),
  Language(name: 'Tibetan', region: 'Tibet'),
  Language(name: 'Turkish', region: 'Turkey'),
  Language(name: 'Turkmen', region: 'Turkmenistan'),
  Language(name: 'Ukrainian', region: 'Ukraine'),
  Language(name: 'Urdu', region: 'Pakistan'),
  Language(name: 'Uzbek', region: 'Uzbekistan'),
  Language(name: 'Vietnamese', region: 'Vietnam'),
  Language(name: 'Welsh', region: 'Wales'),
  Language(name: 'Wu', region: 'China'),
  Language(name: 'Xhosa', region: 'South Africa'),
  Language(name: 'Yiddish', region: 'Jewish Communities'),
  Language(name: 'Yoruba', region: 'Nigeria'),
  Language(name: 'Zulu', region: 'South Africa'),
];